/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateIndexRouteImport } from './routes/create.index'
import { Route as CreatePreviewRouteImport } from './routes/create.preview.'
import { Route as CreateFillRouteImport } from './routes/create.fill.'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePreviewRoute = CreatePreviewRouteImport.update({
  id: '/create/preview/',
  path: '/create/preview/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateFillRoute = CreateFillRouteImport.update({
  id: '/create/fill/',
  path: '/create/fill/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create/': typeof CreateIndexRoute
  '/create/fill/': typeof CreateFillRoute
  '/create/preview/': typeof CreatePreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateIndexRoute
  '/create/fill': typeof CreateFillRoute
  '/create/preview': typeof CreatePreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create/': typeof CreateIndexRoute
  '/create/fill/': typeof CreateFillRoute
  '/create/preview/': typeof CreatePreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create/' | '/create/fill/' | '/create/preview/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create' | '/create/fill' | '/create/preview'
  id: '__root__' | '/' | '/create/' | '/create/fill/' | '/create/preview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateIndexRoute: typeof CreateIndexRoute
  CreateFillRoute: typeof CreateFillRoute
  CreatePreviewRoute: typeof CreatePreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/preview/': {
      id: '/create/preview/'
      path: '/create/preview'
      fullPath: '/create/preview/'
      preLoaderRoute: typeof CreatePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/fill/': {
      id: '/create/fill/'
      path: '/create/fill'
      fullPath: '/create/fill/'
      preLoaderRoute: typeof CreateFillRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateIndexRoute: CreateIndexRoute,
  CreateFillRoute: CreateFillRoute,
  CreatePreviewRoute: CreatePreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
