/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as AuthDemoRouteImport } from './routes/auth-demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateIndexRouteImport } from './routes/create.index'
import { Route as CreatePreviewSlugRouteImport } from './routes/create.preview.$slug'
import { Route as CreateFillSlugRouteImport } from './routes/create.fill.$slug'

const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDemoRoute = AuthDemoRouteImport.update({
  id: '/auth-demo',
  path: '/auth-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePreviewSlugRoute = CreatePreviewSlugRouteImport.update({
  id: '/create/preview/$slug',
  path: '/create/preview/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateFillSlugRoute = CreateFillSlugRouteImport.update({
  id: '/create/fill/$slug',
  path: '/create/fill/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-demo': typeof AuthDemoRoute
  '/invitations': typeof InvitationsRoute
  '/create/': typeof CreateIndexRoute
  '/create/fill/$slug': typeof CreateFillSlugRoute
  '/create/preview/$slug': typeof CreatePreviewSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-demo': typeof AuthDemoRoute
  '/invitations': typeof InvitationsRoute
  '/create': typeof CreateIndexRoute
  '/create/fill/$slug': typeof CreateFillSlugRoute
  '/create/preview/$slug': typeof CreatePreviewSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth-demo': typeof AuthDemoRoute
  '/invitations': typeof InvitationsRoute
  '/create/': typeof CreateIndexRoute
  '/create/fill/$slug': typeof CreateFillSlugRoute
  '/create/preview/$slug': typeof CreatePreviewSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-demo'
    | '/invitations'
    | '/create/'
    | '/create/fill/$slug'
    | '/create/preview/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-demo'
    | '/invitations'
    | '/create'
    | '/create/fill/$slug'
    | '/create/preview/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth-demo'
    | '/invitations'
    | '/create/'
    | '/create/fill/$slug'
    | '/create/preview/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthDemoRoute: typeof AuthDemoRoute
  InvitationsRoute: typeof InvitationsRoute
  CreateIndexRoute: typeof CreateIndexRoute
  CreateFillSlugRoute: typeof CreateFillSlugRoute
  CreatePreviewSlugRoute: typeof CreatePreviewSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-demo': {
      id: '/auth-demo'
      path: '/auth-demo'
      fullPath: '/auth-demo'
      preLoaderRoute: typeof AuthDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/preview/$slug': {
      id: '/create/preview/$slug'
      path: '/create/preview/$slug'
      fullPath: '/create/preview/$slug'
      preLoaderRoute: typeof CreatePreviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/fill/$slug': {
      id: '/create/fill/$slug'
      path: '/create/fill/$slug'
      fullPath: '/create/fill/$slug'
      preLoaderRoute: typeof CreateFillSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthDemoRoute: AuthDemoRoute,
  InvitationsRoute: InvitationsRoute,
  CreateIndexRoute: CreateIndexRoute,
  CreateFillSlugRoute: CreateFillSlugRoute,
  CreatePreviewSlugRoute: CreatePreviewSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
